### PR TITLE
WEBSITE-386 Hostname for cislaves

### PR DESCRIPTION
**Pull request by DavideD**
https://hibernate.atlassian.net/browse/WEBSITE-386
 https://hibernate.atlassian.net/browse/WEBSITE-387

### CODE REVIEW

**Comment by Sanne** [comment]
Did you already apply this one?

**Comment by DavideD** [comment]
> Did you already apply this one?

Yes

**Comment by DavideD** [comment]
@Sanne does this require other changes?

**Comment by Sanne** [comment]
no, looks good I think. Rebased and merged!

**Pull request closed without merging**
