### PR TITLE
Collecting all yum executions for slaves in one for the sake of performance

### PR DESCRIPTION
**Pull request by gunnarmorling**
@Sanne It's not as nice "semantically", but running all yum executions within one transaction gives a nice speed-up.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@Sanne pushed one more commit for installing CouchDB via yum for now. Docker continues to fail with intermittend errors related to device mapper (maybe this issue is related: https://github.com/docker/docker/issues/4036), and I think it's best to wait until there is a new Docker release which run more stable.

**Comment by Sanne** [comment]
Hi @gunnarmorling , sorry I don't agree with the yum refactoring. Speed is definitely not a point, maintainability is the priority and after now creating a couple more machines for other reasons I'd actually prefer to split out each database support into a different role.

I'll apply your "ll" alias, but remember you shouldn't ever need to actually login to these.

About the CouchDB not running in Docker.. why we rung MongoDB in it if it's not ready for that?
I'd rather get rid of Docker at this point, and rather use Docker only for developer images (for developers to run locally).

**Comment by Sanne** [comment]
merged, except the yum executions merge

**Comment by gunnarmorling** [comment]
> sorry I don't agree with the yum refactoring. Speed is definitely not a point

Sanne, please let's come in the future to a consensus in case of disagreements prior to just altering a proposed change and moving ahead. No biggie in this case, but it should be a general base for working together. Remember, this is infrastructure we all contribute to and we all use.

Speed is for sure a point; If setting up things takes painfully long, it will create a barrier for improving this stuff and eventually people will run yum manually on nodes if the automated way blocks their flow. Regarding different roles, sure, we can look into it, but it seems like overkill to me. If it weren't for the issues with Docker, starting all these services on demand still appears as the best option to me (not only for Couch/MongoDB, but also for SQL databases).

> why we rung MongoDB in it if it's not ready for that

The OGM jobs run Mongo via that Maven plug-in, just as it was the case before. There is no equivalent plug-in for CouchDB hence the install. I'm quite happy with Docker as is, it is not really used by any jobs atm. We could remove it from the set-up, but having the package around does do no harm.

**Comment by Sanne** [comment]
> Sanne, please let's come in the future to a consensus in case of disagreements prior to just altering a proposed change and moving ahead. No biggie in this case, but it should be a general base for working together. Remember, this is infrastructure we all contribute to and we all use.

Yea I agree, sorry I made a practical call to cleanup the PR block to not let them hanging here as we switch to other topics.
It was also conflicting with other changes I needed urgently, and not having much time now. I wouldn't have done this shameful move if I wasn't sure it would be trivial to repeat your change in case we agree to do it one day, so it was more like to get your other improvements in asap ;)

I agree speed is nice, but the benefit is too low imho. Happy to rediscuss this in future when we learn more about it. I'm definitely not sitting in front of the screen waiting when it runs.. 15 minutes or 15m:20s is the same for me.

> The OGM jobs run Mongo via that Maven plug-in, just as it was the case before. There is no equivalent plug-in for CouchDB hence the install. I'm quite happy with Docker as is, it is not really used by any jobs atm. We could remove it from the set-up, but having the package around does do no harm.

Ok, thanks I got confused. I thought Mongo would be used via the non-plugin ultimately. I'd like to have both options at some point.

**Pull request closed without merging**
