### PR TITLE
Rsync script

### PR DESCRIPTION
**Pull request by Sanne**
# Just as a TODO reference

The rsync script template with the task to create it, to be cleaned up according to @gunnarmorling 's comments by @DavideD who volunteered..

See only the last commit, the remaining commits are a copy of the current open PR.

### CODE REVIEW

**Comment by Sanne** [comment]
See also implementation notes on https://github.com/hibernate/ci.hibernate.org/pull/16

**Comment by emmanuelbernard** [comment]
This one can go after #16 right?

**Comment by Sanne** [comment]
I'm not understanding what you mean. #16 is closed?

**Comment by Sanne** [comment]
ok, understood now, sorry. Replaced by pr #23

**Pull request closed without merging**
