### PR TITLE
WEBSITE-305 Install couchbase

### PR DESCRIPTION
**Pull request by DavideD**
https://hibernate.atlassian.net/browse/WEBSITE-305

Not sure if you have some preferences about credentials, bucket name or options but it should be easy to change.

At the moment it will create a bucket 'default-bucket' and a user 'Administrator' with password 'password'

I've also added some tools to the common requirement, in particular when checking 'ci.hibernate.org' I find very useful to have vim, mc and htop. They are in separate commits, so feel free to not include them if you prefer.

### CODE REVIEW

**Comment by emmanuelbernard** [comment]
So these bucket and user names, are they influencing how to start the Jenkins job for Hibernate OGM jobs @DavideD ?

**Comment by DavideD** [comment]
They are the credentials and "database" name to connect to CouchBase. It should not have an impact on the existing Jenkins Job because we don't have test trying to connect to it yet.

**Comment by Sanne** [comment]
Could you remove those dangerous first 3 commits as well?

**Comment by Sanne** [comment]
What's the status about this one?

**Comment by DavideD** [comment]
> What's the status about this one?

THere are some thing to change, there is also a new couchbase out

**Comment by gunnarmorling** [comment]
@DavideD I suppose we can discard this one by now?

**Comment by DavideD** [comment]
> @DavideD I suppose we can discard this one by now?

I suppose we can

**Pull request closed without merging**
