### PR TITLE
Update DNS

### PR DESCRIPTION
**Pull request by DavideD**
Update the DNS and remove slave2 from the list of hosts

### CODE REVIEW

**Comment by DavideD** [comment]
@Sanne 
Can you have a quick look at this one?

**Comment by Sanne** [comment]
+1 seems simple enough

**Comment by DavideD** [comment]
Thanks, always a good idea to double check :)

**Comment by DavideD** [comment]
Merged https://github.com/hibernate/ci.hibernate.org/pull/31

**Pull request closed without merging**
