### PR TITLE
WEBSITE-419 Journald

### PR DESCRIPTION
**Pull request by DavideD**
https://hibernate.atlassian.net/browse/WEBSITE-419

Update JournalD configuration on slaves

### CODE REVIEW

**Comment by Sanne** [comment]
- how to apply it? does it need a notification to trigger a machine reboot?

**Comment by Sanne** [comment]
See also:
 - systemd-journald.service

It seems you need to run
    systemctl restart systemd-journald

as a notification listener (only in case the file was changed),
then it would be nice to remove the old file too.

**Comment by DavideD** [comment]
I've updated the pull request, now it restart the service

**Comment by DavideD** [comment]
> then it would be nice to remove the old file too.

Which old file?

**Comment by Sanne** [comment]
merged, thanks!

**Pull request closed without merging**
